management:
  metrics:
  export:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus,info,metrics,threaddump


logging:
  path: /tmp/log/service-glue
